INSERT INTO `operation_web`
(`id`, `name`, `type`, `from`, `element`, `data`, `code`, `description`, `project_id`, `update_user`, `create_user`, `create_time`, `update_time`)
VALUES
(UUID(), 'For循环', 'looper', 'system', '[]', '[{\"type\": \"Int\", \"paramName\": \"steps\", \"description\": \"循环步骤数 本步骤之后的n行\"}, {\"type\": \"String\", \"paramName\": \"indexName\", \"description\": \"循环索引名 记录第几次循环[0,n)\"}, {\"type\": \"Int\", \"paramName\": \"times\", \"description\": \"循环总次数 支持变量如{{name}}\"}]', '', 'for index in range(times)', 'system', 'system_admin_user', 'system_admin_user', REPLACE(unix_timestamp(current_timestamp(3)),'.',''), REPLACE(unix_timestamp(current_timestamp(3)),'.','')),
(UUID(), 'While循环', 'looper', 'system', '[]', '[{\"type\": \"Int\", \"paramName\": \"steps\", \"description\": \"循环步骤数 本步骤之后的n行\"}, {\"type\": \"String\", \"paramName\": \"indexName\", \"description\": \"循环索引名 记录第几次循环[0,n)\"},{\"type\": \"String\", \"paramName\": \"target\", \"description\": \"判断目标 如{{name}}\"}, {\"type\": \"String\", \"paramName\": \"assertion\", \"description\": \"判断方法\"}, {\"type\": \"String\", \"paramName\": \"expect\", \"description\": \"预期值 支持变量如{{name}}\"}, {\"type\": \"Int\", \"paramName\": \"timeout\", \"description\": \"超时时间 单位ms\"}]', '', 'while time < timeout and target assertion expect', 'system', 'system_admin_user', 'system_admin_user', REPLACE(unix_timestamp(current_timestamp(3)),'.',''), REPLACE(unix_timestamp(current_timestamp(3)),'.',''));


INSERT INTO `operation_app`
(`id`, `name`, `type`, `from`, `system`, `element`, `data`, `code`, `description`, `project_id`, `update_user`, `create_user`, `create_time`, `update_time`)
VALUES
(UUID(), 'For循环', 'looper', 'system', 'common', '[]', '[{\"type\": \"Int\", \"paramName\": \"steps\", \"description\": \"循环步骤数 本步骤之后的n行\"}, {\"type\": \"String\", \"paramName\": \"indexName\", \"description\": \"循环索引名 记录第几次循环[0,n)\"}, {\"type\": \"Int\", \"paramName\": \"times\", \"description\": \"循环总次数 支持变量如{{name}}\"}]', '', 'for index in range(times)', 'system', 'system_admin_user', 'system_admin_user', REPLACE(unix_timestamp(current_timestamp(3)),'.',''), REPLACE(unix_timestamp(current_timestamp(3)),'.','')),
(UUID(), 'While循环', 'looper', 'system', 'common', '[]', '[{\"type\": \"Int\", \"paramName\": \"steps\", \"description\": \"循环步骤数 本步骤之后的n行\"}, {\"type\": \"String\", \"paramName\": \"indexName\", \"description\": \"循环索引名 记录第几次循环[0,n)\"},{\"type\": \"String\", \"paramName\": \"target\", \"description\": \"判断目标 如{{name}}\"}, {\"type\": \"String\", \"paramName\": \"assertion\", \"description\": \"判断方法\"}, {\"type\": \"String\", \"paramName\": \"expect\", \"description\": \"预期值 支持变量如{{name}}\"}, {\"type\": \"Int\", \"paramName\": \"timeout\", \"description\": \"超时时间 单位ms\"}]', '', 'while time < timeout and target assertion expect', 'system', 'system_admin_user', 'system_admin_user', REPLACE(unix_timestamp(current_timestamp(3)),'.',''), REPLACE(unix_timestamp(current_timestamp(3)),'.',''));

