CREATE TABLE `assertion` (
    `id`       VARCHAR(50) NOT NULL COMMENT '断言函数英文',
	`name`	   VARCHAR(20) NOT NULL COMMENT '断言函数中文',
    PRIMARY KEY (`id`), UNIQUE(`name`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE utf8mb4_general_ci;

INSERT INTO `assertion` (`id`, `name`) VALUES
('equals', '相等'),
('equalsList', '数组相等'),
('equalsDict', '对象相等'),
('equalsNumber', '数字相等'),
('equalIgnoreCase', '相等(忽略大小写)'),
('notEqual', '不相等'),
('isGreaterThan', '大于'),
('isGreaterThanOrEqualTo', '大于等于'),
('isLessThan', '小于'),
('isLessThanOrEqualTo', '小于等于'),
('isBetween', '在...之间'),
('contains', '包含'),
('notContains', '不包含'),
('containsOnly', '仅包含'),
('isNone', 'none/null'),
('notEmpty', '不为空'),
('empty', '为空'),
('isTrue', 'true'),
('isFalse', 'false'),
('isStrType', '字符串'),
('isIntType', '整数'),
('isFloatType', '浮点数'),
('isInt', '仅含数字'),
('isLetter', '仅含字母'),
('isLower', '小写'),
('isUpper', '大写'),
('startWith', '开头是'),
('endWith', '结尾是'),
('isIn', '被包含'),
('isNotIn', '不被包含'),
('isNotZero', '非0'),
('isZero', '为0'),
('isPositive', '正数'),
('isNegative', '负数'),
('isCloseTo', '接近于'),
('listLenEqual', '列表长度相等'),
('listLenGreaterThan', '列表长度大于'),
('listLenLessThan', '列表长度小于');
